POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "irvingenrique164@gamil.com",
    "password": "irving2003#"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaXNfYWRtaW4iOjEsImlhdCI6MTczNDAyMzg3OCwiZXhwIjoxNzM0MDI0MTc4fQ.Og3EifzIg6QfGA2HnWnWeUIyBdpMcjfItvNJ1yc7TLY