GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/5 

###
POST http://localhost:3000/usuarios/
content-type: application/json

{
    "nombre": "Irving",
    "apellidos": "Vital",
    "email": "irvingenrique164@gmail.com"
}

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nombre": "Juan",
    "apellidos": "Aguilar",
    "email": "juanaguilar198@gmail.com"
}
